import './components/fields.js';
import './components/form-slider.js';
import './components/slider.js';
import './components/upload.js';
import './components/alert.js';
import './components/choices.js';
import './components/dropdown.js';
import './components/offcanvas.js';
import './components/modal.js';